{% set name = "czmodel" %}
{% set version = "5.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/czmodel-{{ version }}.tar.gz
  sha256: d0aee4aa6e0e20719aaf95514ba5fd435d5aeb7d2acbf8c8465c6f4f79dbe167

build:
  entry_points:
    - savedmodel2czann=czmodel.core.convert:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - defusedxml
    - numpy
    - onnx
    - python >={{ python_min }},<3.10
    - pytorch
    - tensorflow >=2,<3,!=2.1
    - tf2onnx
    - xmltodict

test:
  imports:
    - czmodel
  commands:
    - pip list
    # - pip check
    - savedmodel2czann
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/czmodel
  summary: A conversion tool for TensorFlow or ONNX ANNs to CZANN
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - goanpeca
